% FILES
Bone1 = 'N_mc1_s_0.4_1.stl';
Bone2 = 'N_trap_s_0.4_1.stl';

% Read STL files
[F_Bone1, V_Bone1] =  STL_ReadFile([dir Bone1],true);
[F_Bone2, V_Bone2] =  STL_ReadFile([dir Bone2],true);

for i=1:length(V_Bone1)
    colrstl1(i,:)=[0.1,0.25,0.81];
end

p = patch('Faces',F_Bone1,'Vertices',V_Bone1,'FaceColor','b');
figure=set(p,'FaceColor','interp', ...
    'FaceVertexCData',colrstl1, ...
    'EdgeColor','interp', ...
    'EdgeColor', 'interp', ...
    'EdgeAlpha', 0, ...
    'CDataMapping', 'scaled',...
    'AmbientStrength', 0.4, ...
    'DiffuseStrength', 0.8, ...
    'SpecularStrength', 0.2, ...
    'SpecularColorReflectance', 0.5, ...
    'FaceLighting', 'gouraud')
