function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 07-Mar-2017 10:50:57

% Create figure
figure1 = figure('NumberTitle','off',...
    'Name','Evolution of the rotation angles');

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'Color',[1 0 0],'DisplayName','Rot_x');
set(plot1(2),'Color',[0 1 0],'DisplayName','Rot_y');
set(plot1(3),'Color',[0 0 1],'DisplayName','Rot_z');
set(plot1(4),'Color',[0 0 0]);

% Create xlabel
xlabel('time (s)');

% Create ylabel
ylabel('Rotation angle (degrees)');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthEastOutside');

